# Generated by Django 4.1.13 on 2024-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('website', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('reviews_count', models.IntegerField()),
                ('reviews_average', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'google_scraped_data',
            },
        ),
    ]
